### ISSUE TITLE
The Lambda index .js does not work with the skill.js or the model/en-US for the custom JSON skill 

### ISSUE THREAD

**Issue by jimshalo10** [alexa/skill-sample-nodejs-the-foodie#1]
when saying "Alexa open the foodie" in TEST section of Alexa Developer console the AWS Lambda Cloud Watch log contains the following error
2018-07-30T13:42:21.233Z 60e9a0db-93fe-11e8-b209-1930942375b6 AskSdk.DynamoDbPersistenceAdapter Error: Could not read item 
AskSdk.DynamoDbPersistenceAdapter Error: Could not read item (amzn1.ask.account.AFN) from table (theFoodie): Requested resource not found

**Comment by mikevocalz** [comment]
im having the same issues

**Comment by jimshalo10** [comment]
@mikevocalz 
My branch now works and the foodie skill is working. I have updates the ASK-CLI instructions 
13 extra commits and many update the information/7-cli.md has the most updates
My fork is [jimshalo10/skill-sample-nodejs-the-foodie](https://github.com/jimshalo10/skill-sample-nodejs-the-foodie)
I dont know if its possible to create a pull request to master alexa/skill-sample-nodejs-the-foodie.

The originator may not approve and I dont have write/update access for pull request.


I suggest you make your own fork or simply clone my fork.
Git-Bash $ git clone https://github.com/jimshalo10/skill-sample-nodejs-the-foodie.git
follow instructions in my [link](https://github.com/jimshalo10/skill-sample-nodejs-the-foodie/blob/master/instructions/7-cli.md)


If I find any more problems I will continue to fix them

**Comment by SleepyDeveloper** [comment]
Thanks for your help! Your changes have been merged into the skill. 

Since the foodie was built, the Alexa Skills are now able to look up the device's timezone using the  [alexa settings api](https://developer.amazon.com/blogs/alexa/post/c2ba44fa-4bd8-4b49-925d-29dbc0330b1e/personalize-your-alexa-skill-with-customer-specific-time-zones-and-measurements-using-the-alexa-settings-apil). 

Today I'll update the skill to use it and I will be removing the dynamoDBClient.js file.
